## Création de la base de données

On va créer les différentes relations de la base de données Logilivres

In [1]:
CREATE TABLE Librairie 
(
    NumLib INT PRIMARY KEY NOT NULL,
    NomLib TEXT,
    AdresseLib TEXT,
    TelLib TEXT
)

In [2]:
SELECT * FROM Librairie

NumLib	NomLib	AdresseLib	TelLib

In [3]:
INSERT INTO Librairie VALUES (1, "Chroniques", "19 rue Camille Desmoulins, 94230 Cachan", "01 41 98 62 62")

In [4]:
INSERT INTO Librairie (NumLib, NomLib, AdresseLib, TelLib)
VALUES  (2, "Fontaine", "88 rue de Sèvres, 75007 Paris", "01 47 83 29 71"),
        (3, "Shakespeare and Company", "37 rue de la Bûcherie, 75005 Paris", "01 43 25 40 93")

In [5]:
INSERT INTO Librairie (NomLib, AdresseLib, TelLib)
VALUES  ("Fontaine", "88 rue de Sèvres, 75007 Paris", "01 47 83 29 71"),
        ("Shakespeare and Company", "37 rue de la Bûcherie, 75005 Paris", "01 43 25 40 93")

Error: NOT NULL constraint failed: Librairie.NumLib

In [6]:
CREATE TABLE Livre 
(
    NumLivre INT PRIMARY KEY NOT NULL,
    NomLivre TEXT,
    AutLivre TEXT,
    EditeurLivre TEXT,
    PrixLivre NUMERIC
);

INSERT INTO Livre (NumLivre, NomLivre, AutLivre, EditeurLivre, PrixLivre)
VALUES  (1, "La Voie des Rois", "Sanderson, Brandon", "Livre de Poche", 11.9),
        (2, "Brindlewood Bay", "Cordova, Jason", "Storyline", 35),
        (3, "Processus 7", "Darlay, Christine", "Nathan", 24.9),
        (4, "SIG UE8", "Hudin, Oona", "Dunod", 39.9),
        (5, "Astronomie et Astrophysique", "Acker, Agnès", "Dunod", 45)

In [7]:
SELECT * FROM Livre

NumLivre	NomLivre	AutLivre	EditeurLivre	PrixLivre
1	La Voie des Rois	Sanderson, Brandon	Livre de Poche	11.9
2	Brindlewood Bay	Cordova, Jason	Storyline	35
3	Processus 7	Darlay, Christine	Nathan	24.9
4	SIG UE8	Hudin, Oona	Dunod	39.9
5	Astronomie et Astrophysique	Acker, Agnès	Dunod	45

In [8]:
CREATE TABLE Commande 
(
    NumComm INT PRIMARY KEY NOT NULL,
    DateComm DATE,
    NumLib INT
);

INSERT INTO Commande (NumComm, DateComm, NumLib)
VALUES  (1, "2026-01-19", 1),
        (2, "2026-01-26", 3),
        (3, "2026-01-31", 1),
        (4, "2026-02-05", 3)

In [9]:
SELECT * FROM Commande

NumComm	DateComm	NumLib
1	2026-01-19	1
2	2026-01-26	3
3	2026-01-31	1
4	2026-02-05	3

In [10]:
CREATE TABLE Contient 
(
    NumComm INT NOT NULL,
    NumLivre INT NOT NULL,
    QuantiteLivre INT
);

INSERT INTO Contient (NumComm, NumLivre, QuantiteLivre)
VALUES  (1,1,10),
        (1,3,100),
        (1,5,20),
        (2,2,10),
        (2,4,20),
        (3,5,110),
        (4,1,20),
        (4,2,10)

In [11]:
SELECT * FROM Contient

NumComm	NumLivre	QuantiteLivre
1	1	10
1	3	100
1	5	20
2	2	10
2	4	20
3	5	110
4	1	20
4	2	10

In [12]:
INSERT INTO Librairie
    VALUES (4,"Bla bla","bla bla","");
    
SELECT * FROM Librairie;

NumLib	NomLib	AdresseLib	TelLib
1	Chroniques	19 rue Camille Desmoulins, 94230 Cachan	01 41 98 62 62
2	Fontaine	88 rue de Sèvres, 75007 Paris	01 47 83 29 71
3	Shakespeare and Company	37 rue de la Bûcherie, 75005 Paris	01 43 25 40 93
4	Bla bla	bla bla

In [13]:
UPDATE Librairie
SET NomLib = "Librairie Chroniques"
WHERE NomLib = "Chroniques";

SELECT * FROM Librairie;

NumLib	NomLib	AdresseLib	TelLib
1	Librairie Chroniques	19 rue Camille Desmoulins, 94230 Cachan	01 41 98 62 62
2	Fontaine	88 rue de Sèvres, 75007 Paris	01 47 83 29 71
3	Shakespeare and Company	37 rue de la Bûcherie, 75005 Paris	01 43 25 40 93
4	Bla bla	bla bla

In [14]:
SELECT * FROM Librairie
WHERE NomLib LIKE "%Chroniques%"

NumLib	NomLib	AdresseLib	TelLib
1	Librairie Chroniques	19 rue Camille Desmoulins, 94230 Cachan	01 41 98 62 62

In [15]:
DELETE FROM Librairie
WHERE NumLib = 4;

SELECT * FROM Librairie;

NumLib	NomLib	AdresseLib	TelLib
1	Librairie Chroniques	19 rue Camille Desmoulins, 94230 Cachan	01 41 98 62 62
2	Fontaine	88 rue de Sèvres, 75007 Paris	01 47 83 29 71
3	Shakespeare and Company	37 rue de la Bûcherie, 75005 Paris	01 43 25 40 93

In [16]:
SELECT EditeurLivre, AutLivre, NomLivre, PrixLivre
FROM Livre
WHERE PrixLivre > 30
ORDER BY EditeurLivre

EditeurLivre	AutLivre	NomLivre	PrixLivre
Dunod	Hudin, Oona	SIG UE8	39.9
Dunod	Acker, Agnès	Astronomie et Astrophysique	45
Storyline	Cordova, Jason	Brindlewood Bay	35

In [17]:
SELECT NomLib, AdresseLib FROM Librairie
ORDER BY NomLib DESC

NomLib	AdresseLib
Shakespeare and Company	37 rue de la Bûcherie, 75005 Paris
Librairie Chroniques	19 rue Camille Desmoulins, 94230 Cachan
Fontaine	88 rue de Sèvres, 75007 Paris

Ecrire la requête permettant d’afficher le numéro de la commande, les livres commandés, leurs prix et leur quantité :

In [22]:
SELECT Contient.NumComm, NomLivre, PrixLivre, QuantiteLivre
FROM Contient
JOIN Livre ON Contient.NumLivre = Livre.NumLivre

NumComm	NomLivre	PrixLivre	QuantiteLivre
1	La Voie des Rois	11.9	10
1	Processus 7	24.9	100
1	Astronomie et Astrophysique	45	20
2	Brindlewood Bay	35	10
2	SIG UE8	39.9	20
3	Astronomie et Astrophysique	45	110
4	La Voie des Rois	11.9	20
4	Brindlewood Bay	35	10

In [23]:
SELECT Contient.NumComm, NomLivre, PrixLivre, QuantiteLivre
FROM Contient, Livre
WHERE Contient.NumLivre = Livre.NumLivre

NumComm	NomLivre	PrixLivre	QuantiteLivre
1	La Voie des Rois	11.9	10
1	Processus 7	24.9	100
1	Astronomie et Astrophysique	45	20
2	Brindlewood Bay	35	10
2	SIG UE8	39.9	20
3	Astronomie et Astrophysique	45	110
4	La Voie des Rois	11.9	20
4	Brindlewood Bay	35	10

Ecrire la requête permettant d’afficher le numéro et la date de la commande, le nom et l’adresse de la librairie, les livres commandés ainsi que leurs prix et leur quantité :

In [24]:
SELECT c.NumComm, DateComm, NomLib, AdresseLib, 
    NomLivre, PrixLivre, QuantiteLivre
FROM Contient c, Livre liv, Librairie lib, Commande com
WHERE c.NumLivre = liv.NumLivre
AND c.NumComm = com.NumComm
AND com.NumLib = lib.NumLib

NumComm	DateComm	NomLib	AdresseLib	NomLivre	PrixLivre	QuantiteLivre
1	2026-01-19	Librairie Chroniques	19 rue Camille Desmoulins, 94230 Cachan	La Voie des Rois	11.9	10
1	2026-01-19	Librairie Chroniques	19 rue Camille Desmoulins, 94230 Cachan	Processus 7	24.9	100
1	2026-01-19	Librairie Chroniques	19 rue Camille Desmoulins, 94230 Cachan	Astronomie et Astrophysique	45	20
2	2026-01-26	Shakespeare and Company	37 rue de la Bûcherie, 75005 Paris	Brindlewood Bay	35	10
2	2026-01-26	Shakespeare and Company	37 rue de la Bûcherie, 75005 Paris	SIG UE8	39.9	20
3	2026-01-31	Librairie Chroniques	19 rue Camille Desmoulins, 94230 Cachan	Astronomie et Astrophysique	45	110
4	2026-02-05	Shakespeare and Company	37 rue de la Bûcherie, 75005 Paris	La Voie des Rois	11.9	20
4	2026-02-05	Shakespeare and Company	37 rue de la Bûcherie, 75005 Paris	Brindlewood Bay	35	10