In [1]:
.schema

sql
CREATE TABLE "joueurs_nba" (
	"Name"	TEXT,
	"Team"	TEXT,
	"Number"	INTEGER,
	"Position"	TEXT,
	"Age"	INTEGER,
	"Height"	INTEGER,
	"Weight"	INTEGER
)

In [2]:
SELECT * FROM joueurs_nba LIMIT 5

Name	Team	Number	Position	Age	Height	Weight
Steven Adams	Houston Rockets	12	C	32	211	120
Bam Adebayo	Miami Heat	13	C	28	206	116
Ochai Agbaji	Toronto Raptors	30	SF	25	196	98
Santi Aldama	Memphis Grizzlies	7	C	24	213	98
Trey Alexander	New Orleans Pelicans	23	SG	23	193	84

2. Tester la requête SQL suivante et exprimer en français de tous les jours la nature de cette requête.

`SELECT AVG(Age) FROM joueurs_nba WHERE Team = "Los Angeles Lakers" ;`

In [5]:
SELECT ROUND(AVG(Age),0) AS "Âge moyen des Lakers" FROM joueurs_nba 
WHERE Team = "Los Angeles Lakers" ;

Âge moyen des Lakers
26

3. Ecrire les requêtes permettant d'avoir :

a. d’obtenir la taille maximum des joueurs de l’équipe des Chicago Bulls ;

In [6]:
SELECT MAX(Height) FROM joueurs_nba
WHERE Team = "Chicago Bulls";

MAX(Height)
211

   b. d’obtenir le poids le plus faible de tous les joueurs de NBA évoluant au poste de Shooting Guard ;

In [7]:
SELECT Name, Team, MIN(Weight) FROM joueurs_nba
WHERE Position = "SG"

Name	Team	MIN(Weight)
Isaiah Joe	Oklahoma City Thunder	75

In [8]:
SELECT * FROM joueurs_nba
WHERE Name = "Isaiah Joe"

Name	Team	Number	Position	Age	Height	Weight
Isaiah Joe	Oklahoma City Thunder	11	SG	26	191	75

In [9]:
SELECT Name, Team, Weight FROM joueurs_nba
WHERE Position = "SG"
AND Weight = 75

Name	Team	Weight
Isaiah Joe	Oklahoma City Thunder	75

c. d’obtenir toutes les informations concernant Victor Wembanyama puis de savoir s’il est le plus jeune des joueurs de NBA de plus de 2m10 (on peut faire deux requêtes séparées) ;

In [10]:
SELECT * FROM joueurs_nba
WHERE Name = "Victor Wembanyama"

Name	Team	Number	Position	Age	Height	Weight
Victor Wembanyama	San Antonio Spurs	1	F	21	221	107

In [12]:
SELECT Name, Team, MIN(Age), Height FROM joueurs_nba
WHERE Height >= 210;

Name	Team	MIN(Age)	Height
Khaman Maluach	Phoenix Suns	19	218

4. Modification de la base de données

a. Écrire la requête SQL permettant de vous ajouter dans la base des données des joueurs de NBA, au sein de l’équipe des Boston Celtics avec le numéro 99 et au poste de Power Forward (ou bien tout autre valeur de votre choix) ;

Vérifier ensuite que l’entrée a bien été ajoutée.

In [14]:
INSERT INTO joueurs_nba 
    VALUES ("Benjamin Pruvost", "Boston Celtics", 99, "PF", 35, 185, 90);

SELECT * FROM joueurs_nba
WHERE Team = "Boston Celtics";

Name	Team	Number	Position	Age	Height	Weight
Chris Boucher	Boston Celtics	25	PF	32	206	91
Jaylen Brown	Boston Celtics	7	SF	28	198	101
Luka Garza	Boston Celtics	52	C	26	208	110
Hugo Gonzalez	Boston Celtics	28	F	19	198	91
Hayden Gray	Boston Celtics		G	22	193	86
Sam Hauser	Boston Celtics	30	SF	27	201	99
R.J. Luis	Boston Celtics	12	F	24	201	98
Josh Minott	Boston Celtics	8	F	22	203	93
Payton Pritchard	Boston Celtics	11	PG	27	185	89
Neemias Queta	Boston Celtics	88	C	26	213	113
Baylor Scheierman	Boston Celtics	55	PG	24	198	93
Max Shulga	Boston Celtics	29	G	24	196	95
Anfernee Simons	Boston Celtics	4	SG	26	191	91
Jayson Tatum	Boston Celtics	0	SF	27	203	95
Xavier Tillman, Sr.	Boston Celtics	26	PF	26	201	111
Jordan Walsh	Boston Celtics	27	F	21	198	93
Derrick White	Boston Celtics	9	G	31	193	86
Amari Williams	Boston Celtics	77	PF	24	211	114
Benjamin Pruvost	Boston Celtics	99	PF	35	185	90
Benjamin Pruvost	Boston Celtics	99	PF	35	185	90

b. On suppose que Nicolas Batum, qui évolue dans l’équipe des Los Angeles Clippers, va rejoindre Victor Wembanyama chez les San Antonio Spurs où il portera alors le numéro 75. Écrire la ou les requête(s) qui permet(tent) de mettre à jour la base de données.

Vérifier ensuite par une requête du type `SELECT * FROM joueurs_nba WHERE Name
= ’Nicolas Batum’` que la mise à jour a bien été effectuée.

In [17]:
UPDATE joueurs_nba
SET Team = "San Antonio Spurs", Number = 75
WHERE Name = 'Nicolas Batum';

SELECT * FROM joueurs_nba
WHERE Name = 'Nicolas Batum';

Name	Team	Number	Position	Age	Height	Weight
Nicolas Batum	San Antonio Spurs	75	F	36	203	104

c. Un plaisantin a pollué la table de données en insérant une équipe Gotham City. Écrire la requête SQL permettant de connaître les noms des joueurs de cette équipe, puis écrire la requête permettant de supprimer ces enregistrements.

In [18]:
SELECT * FROM joueurs_nba
WHERE Team = "Gotham City";

Name	Team	Number	Position	Age	Height	Weight
Batman	Gotham City	77	PF	25	182	78
Robin	Gotham City	21	SF	19	172	69
Wonder Woman	Gotham City	6	PG	22	174	63

In [ ]:
DELETE FROM joueurs_nba
WHERE Team = "Gotham City";

SELECT * FROM joueurs_nba
WHERE Team = "Gotham City";